import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve('site');
const domain = 'https://drfelipemachadoplastica.com.br';
const ready = process.env.SITE_READY === 'true';
const required = ['CRM_PE', 'RQE', 'CLINIC_REGISTRATION', 'PRIVACY_EMAIL', 'LEAD_WEBHOOK_URL', 'META_CUSTOM_EVENT_NAME'];
if (process.env.VERCEL_ENV === 'production' && (!ready || required.some(k => !process.env[k]))) {
  throw new Error(`Publicação bloqueada. Confirme SITE_READY=true e configure: ${required.join(', ')}.`);
}
const escape = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const crm = process.env.CRM_PE ? `MÉDICO · CRM-PE ${escape(process.env.CRM_PE)}` : 'MÉDICO · [CONFIRMAR: CRM-PE]';
const rqe = process.env.RQE ? `RQE ${escape(process.env.RQE)}` : '[CONFIRMAR: RQE]';
const reg = process.env.CLINIC_REGISTRATION ? `Registro da clínica: ${escape(process.env.CLINIC_REGISTRATION)}` : '[CONFIRMAR: registro da clínica]';
const privacy = process.env.PRIVACY_EMAIL ? escape(process.env.PRIVACY_EMAIL) : '[CONFIRMAR: e-mail de privacidade]';
const procedures = [
  {slug:'mastopexia',name:'Mastopexia',intro:'Uma conversa sobre forma, posição das mamas e o que faz sentido para o seu corpo.',what:'A mastopexia é uma cirurgia para reposicionar as mamas e tratar a flacidez. A necessidade de prótese, a técnica e as cicatrizes possíveis são avaliadas individualmente.',for:'Pode ser considerada por quem percebe queda das mamas e deseja entender as opções cirúrgicas. A indicação depende da avaliação médica.',recovery:'O tempo de recuperação e as orientações variam conforme a técnica e as condições de cada pessoa. Esses detalhes são definidos na consulta.',q:'A mastopexia sempre precisa de prótese?',a:'Não. A indicação de prótese depende da anatomia, das expectativas e da avaliação médica.'},
  {slug:'protese-de-mama',name:'Prótese de mama',intro:'Volume e proporção começam com uma avaliação cuidadosa.',what:'A cirurgia com implante mamário busca modificar o volume das mamas. Escolha do implante, posicionamento e via de acesso são decisões individuais.',for:'Pode ser uma opção para quem deseja conversar sobre volume mamário. A consulta permite avaliar indicações, limites e alternativas.',recovery:'A recuperação depende do plano cirúrgico e da resposta de cada paciente. O acompanhamento e as orientações são explicados antes da cirurgia.',q:'Existe um tamanho ideal de prótese?',a:'Não existe uma medida única. A escolha considera anatomia, proporções e objetivos discutidos na consulta.'},
  {slug:'lipo-hd',name:'Lipo HD',intro:'Planejamento do contorno corporal com indicação individual.',what:'A lipoaspiração de alta definição é uma técnica de contorno corporal. Ela não substitui perda de peso nem garante um formato específico.',for:'A possibilidade de cirurgia depende de avaliação clínica, distribuição de gordura e expectativas realistas.',recovery:'O pós-operatório pode incluir malha, acompanhamento e restrição temporária de atividades. O plano é individual.',q:'Lipo HD é indicada para emagrecer?',a:'Não. A lipoaspiração é um procedimento de contorno corporal e não um tratamento para emagrecimento.'},
  {slug:'abdominoplastia',name:'Abdominoplastia',intro:'Avaliação da pele, da parede abdominal e dos objetivos de cada paciente.',what:'A abdominoplastia trata excesso de pele abdominal e pode envolver reparo da musculatura, quando indicado. A técnica depende da avaliação presencial.',for:'Pode ser discutida quando há flacidez abdominal que não melhora com medidas não cirúrgicas. A indicação é individual.',recovery:'O período de recuperação e as limitações variam. A consulta esclarece cuidados, cicatriz, riscos e acompanhamento.',q:'Abdominoplastia pode ser combinada com lipoaspiração?',a:'Em alguns casos, sim. A segurança e a indicação de procedimentos combinados exigem avaliação médica.'}
];
const faq = [
  ['Como agendar uma consulta?','Você pode chamar a equipe pelo WhatsApp ou enviar o formulário. O agendamento depende da disponibilidade da unidade escolhida.'],
  ['O atendimento acontece em quais cidades?','O atendimento é informado para Recife e Caruaru. Confirme local, endereço e horário com a equipe antes de se deslocar.'],
  ['Posso combinar cirurgias?','Algumas combinações são possíveis, mas a indicação depende da avaliação de saúde, do plano cirúrgico e dos riscos envolvidos.'],
  ['Quando saberei qual procedimento é indicado?','A indicação vem após consulta e avaliação individual. As informações deste site servem para orientar sua conversa com o médico.'],
  ['Como é o acompanhamento após a cirurgia?','O plano de acompanhamento e os retornos são explicados durante a consulta e ajustados ao procedimento realizado.']
];
const json = value => JSON.stringify(value).replace(/</g,'\\u003c');
const writePage = (slug, html) => { const folder=resolve(root,slug); mkdirSync(folder,{recursive:true}); writeFileSync(resolve(folder,'index.html'),html); };
const schema = (path, questions=[]) => [
  { '@context':'https://schema.org','@type':['Physician','MedicalBusiness'],name:'Dr. Felipe Machado',url:domain+path,description:'Informações sobre consultas e cirurgia plástica em Recife e Caruaru.',areaServed:[{ '@type':'City',name:'Recife'},{'@type':'City',name:'Caruaru'}],medicalSpecialty:'PlasticSurgery',image:domain+'/assets/GRID-LP-FELIPE-MACHADO.webp',telephone:'+55 81 9170-9654' },
  ...(questions.length ? [{ '@context':'https://schema.org','@type':'FAQPage',mainEntity:questions.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}})) }] : [])
];
const wa = (label, slug='') => `<a class="button button-primary wa-link" data-procedure="${slug}" href="https://wa.me/558191709654?text=${encodeURIComponent('Olá! Gostaria de agendar uma consulta com o Dr. Felipe Machado'+(slug?' sobre '+label.toLowerCase():'')+'.')}">${label}</a>`;
const header = `<header class="header"><div class="wrap nav"><a class="brand" href="/" aria-label="Dr. Felipe Machado, página inicial"><span class="monogram">FM</span><span>Felipe<br><strong>Machado</strong></span></a><nav aria-label="Navegação principal"><a href="/#procedimentos">Procedimentos</a><a href="/#sobre">Sobre</a><a href="/#consulta">Consulta</a><a href="/#unidades">Unidades</a></nav><a class="nav-cta" href="/#contato">Agendar consulta <span aria-hidden="true">↗</span></a></div></header>`;
const footer = `<footer class="footer"><div class="wrap footer-grid"><div><span class="footer-name">Dr. Felipe Machado</span><p>Cirurgia plástica em Recife e Caruaru.</p><p>${crm} · ${rqe}<br>${reg}</p></div><div><h2>Explore</h2><a href="/#procedimentos">Procedimentos</a><a href="/#consulta">Como funciona</a><a href="/politica-de-privacidade/">Política de privacidade</a></div><div><h2>Fale com a equipe</h2><p>WhatsApp: (81) 99170-9654</p>${wa('Conversar no WhatsApp')}</div></div><div class="wrap footer-bottom"><span>© ${new Date().getFullYear()} Dr. Felipe Machado</span><span>Conteúdo informativo. Não substitui a consulta médica.</span></div></footer>`;
const form = (selected='') => `<form class="lead-form" id="lead-form" novalidate><h3>Vamos conversar?</h3><p>Deixe seus dados para a equipe entrar em contato.</p><label for="name">Nome</label><input id="name" name="name" autocomplete="name" required maxlength="100"><label for="phone">WhatsApp</label><input id="phone" name="phone" type="tel" inputmode="tel" autocomplete="tel" required maxlength="20" placeholder="(81) 99999-9999"><div class="form-row"><div><label for="procedure">Procedimento</label><select id="procedure" name="procedure"><option value="">Selecione</option>${procedures.map(p=>`<option value="${p.slug}" ${selected===p.slug?'selected':''}>${p.name}</option>`).join('')}</select></div><div><label for="city">Cidade</label><select id="city" name="city"><option value="">Selecione</option><option>Recife</option><option>Caruaru</option><option>Outra cidade</option></select></div></div><div class="trap" aria-hidden="true"><label for="website">Site</label><input id="website" name="website" tabindex="-1" autocomplete="off"></div><label class="consent"><input type="checkbox" name="consent" required> Li a <a href="/politica-de-privacidade/">política de privacidade</a> e autorizo o contato sobre minha solicitação.</label><button class="button button-primary" type="submit">Pedir contato <span aria-hidden="true">↗</span></button><p class="form-status" role="status" aria-live="polite"></p></form>`;
function page({title,description,path,body,questions=[]}) {
 const data=schema(path,questions);
 return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(title)}</title><meta name="description" content="${escape(description)}"><link rel="canonical" href="${domain+path}"><meta property="og:type" content="website"><meta property="og:locale" content="pt_BR"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${domain+path}"><meta property="og:image" content="${domain}/assets/GRID-LP-FELIPE-MACHADO.webp"><meta name="theme-color" content="#1F2B53"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Sora:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/style.css"><script type="application/ld+json">${json(data)}</script><script defer src="/config.js"></script><script defer src="/site.js"></script></head><body><a class="skip" href="#main">Pular para o conteúdo</a>${header}<main id="main">${body}</main>${footer}</body></html>`;
}
const faqHtml = items => `<div class="faq-list">${items.map(([q,a])=>`<details><summary>${escape(q)}</summary><p>${escape(a)}</p></details>`).join('')}</div>`;
const cards = procedures.map((p,i)=>`<a class="procedure-card" href="/${p.slug}/"><span class="card-number">0${i+1} / 04</span><h3>${p.name}</h3><p>${p.intro}</p><span class="text-link">Entenda o procedimento <span aria-hidden="true">↗</span></span></a>`).join('');
const home = `<section class="hero"><div class="wrap hero-grid"><div class="hero-copy"><p class="eyebrow light">CIRURGIA PLÁSTICA · RECIFE E CARUARU</p><h1>Cirurgia plástica começa com uma boa conversa.</h1><p class="lead">O Dr. Felipe Machado atende quem deseja entender as possibilidades de um procedimento com orientação individual e expectativas realistas.</p><p class="credentials">${crm} <span>·</span> ${rqe}</p><div class="actions">${wa('Conversar no WhatsApp')}<a class="button button-outline" href="#contato">Deixar meu contato</a></div><p class="hero-note">Cada indicação depende de consulta e avaliação médica.</p></div></div></section>
<section class="section" id="procedimentos"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">PROCEDIMENTOS</p><h2>Conheça as possibilidades</h2></div><p>Informações para ajudar você a chegar à consulta com perguntas melhores.</p></div><div class="card-grid">${cards}</div></div></section>
<section class="about section" id="sobre"><div class="wrap about-grid"><div class="about-photo"><img src="/assets/Felipe.webp" width="370" height="586" loading="lazy" alt="Retrato em preto e branco do Dr. Felipe Machado"></div><div class="about-copy"><p class="eyebrow light">SOBRE O MÉDICO</p><h2>Uma avaliação para cada pessoa.</h2><p>Antes de falar em técnica, é preciso ouvir o que você espera e avaliar o que é indicado para o seu caso. O Dr. Felipe Machado atende em Recife e Caruaru.</p><div class="about-points"><div><strong>Escuta</strong><span>Suas dúvidas e objetivos fazem parte da consulta.</span></div><div><strong>Planejamento</strong><span>Indicações e limites são discutidos de forma individual.</span></div><div><strong>Acompanhamento</strong><span>O cuidado continua depois do procedimento.</span></div></div><p class="credentials">${crm} · ${rqe}</p>${wa('Agendar uma consulta')}</div></div></section>
<section class="section process" id="consulta"><div class="wrap"><p class="eyebrow">SUA JORNADA</p><h2>Como funciona a consulta</h2><div class="steps"><div><span>01</span><h3>Conversa inicial</h3><p>Você conta o que procura e tira as primeiras dúvidas.</p></div><div><span>02</span><h3>Avaliação</h3><p>O médico examina seu caso, histórico de saúde e possibilidades.</p></div><div><span>03</span><h3>Planejamento</h3><p>Se houver indicação, técnica, riscos e recuperação são discutidos.</p></div><div><span>04</span><h3>Acompanhamento</h3><p>Os retornos são definidos de acordo com o procedimento.</p></div></div></div></section>
<section class="section units" id="unidades"><div class="wrap"><p class="eyebrow">ONDE ATENDEMOS</p><h2>Recife e Caruaru</h2><p>Consulte a equipe para confirmar endereço, disponibilidade e horário da unidade desejada.</p><div class="unit-grid"><div><span class="unit-index">01</span><h3>Recife</h3><p>Endereço e horários informados no agendamento.</p>${wa('Perguntar sobre Recife')}</div><div><span class="unit-index">02</span><h3>Caruaru</h3><p>Endereço e horários informados no agendamento.</p>${wa('Perguntar sobre Caruaru')}</div></div></div></section>
<section class="section faq" id="faq"><div class="wrap narrow"><p class="eyebrow">DÚVIDAS FREQUENTES</p><h2>Antes de marcar sua consulta</h2>${faqHtml(faq)}</div></section>
<section class="contact section" id="contato"><div class="wrap contact-grid"><div><p class="eyebrow light">PRÓXIMO PASSO</p><h2>Conte o que você gostaria de conversar na consulta.</h2><p>Preencha o formulário ou fale diretamente com a equipe pelo WhatsApp.</p>${wa('Abrir WhatsApp')}</div>${form()}</div></section>`;
writeFileSync(resolve(root,'index.html'),page({title:'Dr. Felipe Machado | Cirurgia plástica em Recife e Caruaru',description:'Conheça os procedimentos e agende uma consulta com o Dr. Felipe Machado em Recife ou Caruaru.',path:'/',body:home,questions:faq}));
for(const p of procedures){
 const body=`<section class="inner-hero"><div class="wrap inner-grid"><div><p class="eyebrow light">PROCEDIMENTOS / ${p.name.toUpperCase()}</p><h1>${p.name}</h1><p class="lead">${p.intro}</p><div class="actions">${wa('Conversar sobre '+p.name,p.slug)}<a class="button button-outline" href="#contato">Pedir contato</a></div></div><div class="inner-portrait"><img src="/assets/Felipe.webp" width="370" height="586" alt="Dr. Felipe Machado" loading="eager"></div></div></section><section class="section"><div class="wrap content-grid"><div><p class="eyebrow">ENTENDA O PROCEDIMENTO</p><h2>O que é ${p.name.toLowerCase()}?</h2><p>${p.what}</p></div><aside class="info-box"><span>01 / 03</span><h3>Para quem pode ser</h3><p>${p.for}</p></aside></div></section><section class="section pale"><div class="wrap content-grid"><div><p class="eyebrow">DEPOIS DA CIRURGIA</p><h2>Recuperação e acompanhamento</h2><p>${p.recovery}</p></div><aside class="info-box"><span>02 / 03</span><h3>Conversa na consulta</h3><p>Leve suas dúvidas. A avaliação inclui indicação, riscos, cicatrizes e cuidados depois do procedimento.</p></aside></div></section><section class="section faq"><div class="wrap narrow"><p class="eyebrow">PERGUNTAS FREQUENTES</p><h2>Dúvidas sobre ${p.name.toLowerCase()}</h2>${faqHtml([[p.q,p.a],...faq.slice(0,2)])}</div></section><section class="contact section" id="contato"><div class="wrap contact-grid"><div><p class="eyebrow light">AGENDE UMA CONVERSA</p><h2>Sua avaliação é individual.</h2><p>Converse com a equipe sobre uma consulta em Recife ou Caruaru.</p>${wa('Falar sobre '+p.name,p.slug)}</div>${form(p.slug)}</div></section>`;
 writePage(p.slug,page({title:`${p.name} em Recife e Caruaru | Dr. Felipe Machado`,description:`Saiba mais sobre ${p.name.toLowerCase()}, avaliação e recuperação. Agende uma consulta com o Dr. Felipe Machado em Recife ou Caruaru.`,path:`/${p.slug}/`,body,questions:[[p.q,p.a],...faq.slice(0,2)]}));
}
const policy=`<section class="inner-hero simple"><div class="wrap"><p class="eyebrow light">PRIVACIDADE</p><h1>Política de privacidade</h1><p>Como tratamos as informações enviadas por este site.</p></div></section><section class="section"><div class="wrap narrow prose"><h2>Dados que você envia</h2><p>O formulário solicita nome, WhatsApp, procedimento de interesse e cidade. Também podemos receber parâmetros de origem da visita, como UTM e fbclid. Não inclua informações de saúde sensíveis no formulário.</p><h2>Finalidade e compartilhamento</h2><p>Usamos esses dados para responder ao pedido de contato e organizar o atendimento. O envio é feito a um serviço de recebimento configurado pelo responsável pelo site. Informações de navegação podem ser processadas pelo Pixel da Meta para medição de campanhas.</p><h2>Seus direitos</h2><p>Você pode solicitar acesso, correção ou exclusão dos seus dados pelo contato de privacidade: ${privacy}. A política e o tempo de retenção devem ser confirmados pelo responsável antes da publicação.</p><h2>Contato</h2><p>Dr. Felipe Machado. ${crm}. Para dúvidas sobre privacidade: ${privacy}.</p></div></section>`;
writePage('politica-de-privacidade',page({title:'Política de privacidade | Dr. Felipe Machado',description:'Informações sobre o tratamento dos dados enviados pelo site do Dr. Felipe Machado.',path:'/politica-de-privacidade/',body:policy}));
writePage('obrigado',page({title:'Contato recebido | Dr. Felipe Machado',description:'Seu pedido de contato foi recebido.',path:'/obrigado/',body:`<section class="thanks"><div class="wrap narrow"><p class="eyebrow">CONTATO RECEBIDO</p><h1>Recebemos sua mensagem.</h1><p>A equipe entrará em contato pelo WhatsApp informado. Se preferir, você também pode iniciar a conversa agora.</p>${wa('Abrir WhatsApp')}<p><a href="/">Voltar à página inicial</a></p></div></section>`}));
writeFileSync(resolve(root,'404.html'),page({title:'Página não encontrada | Dr. Felipe Machado',description:'A página solicitada não foi encontrada.',path:'/404/',body:`<section class="thanks"><div class="wrap narrow"><p class="eyebrow">ERRO 404</p><h1>Não encontramos esta página.</h1><p>Confira o endereço ou volte para conhecer os procedimentos.</p><a class="button button-primary" href="/">Voltar ao início</a></div></section>`}));
const paths=['/','/mastopexia/','/protese-de-mama/','/lipo-hd/','/abdominoplastia/','/politica-de-privacidade/'];
writeFileSync(resolve(root,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${paths.map(path=>`<url><loc>${domain+path}</loc></url>`).join('')}</urlset>`);
writeFileSync(resolve(root,'robots.txt'),`User-agent: *\nAllow: /\nDisallow: /obrigado/\nSitemap: ${domain}/sitemap.xml\n`);
writeFileSync(resolve(root,'llms.txt'),`# Dr. Felipe Machado\n\nInformações sobre consulta e cirurgia plástica em Recife e Caruaru. O conteúdo é informativo e não substitui avaliação médica.\n\n- Site: ${domain}/\n- Procedimentos: ${paths.slice(1,5).map(p=>domain+p).join(', ')}\n- Privacidade: ${domain}/politica-de-privacidade/\n`);
writeFileSync(resolve(root,'config.js'),`window.SITE_CONFIG=${json({customEvent:process.env.META_CUSTOM_EVENT_NAME||''})};\n`);
console.log(`Geradas ${paths.length+2} páginas. Publicação ${ready?'marcada como pronta':'bloqueada até confirmação dos dados'}.`);
